[package]
name = "b3-platform"
version = "0.1.0"
edition = "2021"

[[example]]
name = "hello-world"
path = "examples/hello_world.rs"

[[example]]
name = "app-menu"
path = "examples/app_menu.rs"

[dependencies]
objc2 = "0.5.1"
objc2-app-kit = {version = "0.2.0", features = ["NSApplication", "NSEvent", "NSMenu", "NSMenuItem", "NSResponder", "NSRunningApplication"]}
objc2-foundation = {version = "0.2.0", features = ["NSNotification", "NSObject", "NSString", "NSThread"]}
